### ISSUE TITLE
No preprocessing code

### ISSUE THREAD

**Issue by candlewill** [MU94W/WaveNet#1]
Is the code complete? I  did not find the preprocessing code. How to generate the pickle file for training? 

https://github.com/MU94W/WaveNet/blob/5ee4abfa624ed36fdb035316496e72d6100bae26/train.py#L36

**Comment by MU94W** [comment]
@candlewill 
The pickle file pickles a dictionary object, which contains the following fields:
"key_lst": list, a list of the names of audio files, e.g. "example0.wav".
"root": str, the path to the root directory that contains all audios listed in "key_lst".
"sr": int, the sampling rate.
I will add the preprocessing code later.

**Comment by candlewill** [comment]
Thanks.
